### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by 2asyeasy** [davidmigloz/multi-state-switch#13]
// => java.lang.IllegalArgumentException
// => BlurMaskFilter(blurRadius.toFloat(), BlurMaskFilter.Blur.NORMAL)
// => blurRadius is zero (???)
 
// => fun createStateDrawable
// => LGE X6 : shadowBottomOverflowPx = 1 , Others : 2
// (AS-IS) val shadowBm = createShadow(stateBm, shadowBottomOverflowPx / 2)
// (TO-BE) val shadowBm = createShadow(stateBm, if (shadowBottomOverflowPx / 2 < 1) 1 else shadowBottomOverflowPx / 2)

---------------------------
Device : LGE X6
OS : Android 10

**Comment by davidmigloz** [comment]
I'll close this issue. Let me know if you are still experiencing the crash.

**Comment by 2asyeasy** [comment]
> I'll close this issue. Let me know if you are still experiencing the crash.

It's an issue that happens with non-mainstream Android devices.

if (shadowBottomOverflowPx < 2) {
    // java.lang.IllegalArgumentException
    // android.graphics.BlurMaskFilter : radius – The radius to extend the blur from the original mask. Must be > 0.
}
