### ISSUE TITLE
transition animation does not work the indicator just jumps to the selected value

### ISSUE THREAD

**Issue by netef** [davidmigloz/multi-state-switch#5]
hi, when i press on a value on the slider the ellipse just jumps on it and doesnt do a cool slide effect. why is this? i tried finding an attribute regarding the issue and couldnt find any.
please help me.
thank you :)

**Comment by davidmigloz** [comment]
Hi @netef ,

As it is currently implemented, the sliding effect only happens when you drag the indicator. If you click a non-selected state it will directly jump there.
