### ISSUE TITLE
Help with theme of this

### ISSUE THREAD

**Issue by Arise** [davidmigloz/multi-state-switch#7]
I would like to change the background color of the widget, but not sure how to access it in my themes.xml

I see it defined as in sources:  ``<item name="multistateswitch_background_color">@color/multistateswitch_light_grey</item>``
and ``MultiStateSwitch_multistateswitch_background_color``

If I want to change this what should I do?

**Comment by Arise** [comment]
I mean I've already added 
``<style name="MyCustomThemeLight" parent="Theme.AppCompat.Light.NoActionBar">
	<item name="multistateswitch_background_color">@color/accent</item>``

But the background is still the whitish color defined in the library (multistateswitch_light_grey : #f2f2f2 )

**Comment by davidmigloz** [comment]
Hi @Arise ,

Here you can find all the XML attributes that it supports:
https://github.com/davidmigloz/multi-state-switch#attributes

Cheers.
